version: '3.4'
services:

  rasa-server:
    image: alpine/git:latest 
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions: /app/actions
    - ./data: /app/data 
    - ./tests: /app/tests
    command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --cors \"*\" --debug"
    ports:
    - '5006:5005'
    public: true
    networks:
    - all

  rasa-actions-server:
    image: alpine/git:latest 
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions: /app/actions
    command: ["rasa", "run", "actions"]
    ports:
    - '5055:5055'
    networks:
    - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"